const ALL_POSTS = "ALL_POSTS";
const POSTS_BY_USER = "POSTS_BY_USER";
const POSTS_BY_TAG = "POSTS_BY_TAG";
const POSTS_BY_DETAILS = "POSTS_BY_DETAILS";

module.exports = { ALL_POSTS, POSTS_BY_USER, POSTS_BY_TAG, POSTS_BY_DETAILS };
